allowBuilds:
    '@nestjs/core': true
    '@scarf/scarf': false
    unrs-resolver: true
autoInstallPeers: false
ignoredBuiltDependencies:
    - '@scarf/scarf'
    - unrs-resolver
onlyBuiltDependencies:
    - '@nestjs/core'
